version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3307"
    ports:
      - "3307:3306"
    volumes:
        - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8085"
    ports:
      - "8085:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
volumes:
  mariadb:
    driver: local
